### ISSUE TITLE
No Input Profile converting from Jpeg to Webp

### ISSUE THREAD

**Issue by augustocdias** [libvips/libvips#1767]
I'm having a problem trying to encode a JPEG to WEBP because of the ICC profile...

```
vips webpsave file.jpeg file.webp
icc_import: no input profile
```

Do I have some operation on the image before trying to reencode it?

Here's the image causing issues
![image](https://user-images.githubusercontent.com/1080789/89421150-f57aef80-d733-11ea-9e4e-f0051f5f6ab7.jpeg)

**Comment by jcupitt** [comment]
Oh no! You're right, a typo broke ICC profile write to webp a few days ago. This should be fixed in git master now.

```
john@kiwi:~/pics$ vipsheader -a small_quagga.jpg | grep icc
icc-profile-data: 560 bytes of binary data
john@kiwi:~/pics$ vips copy small_quagga.jpg x.webp
john@kiwi:~/pics$ vipsheader -a x.webp | grep icc
icc-profile-data: 560 bytes of binary data
```

I'll add a test too.

**Comment by jcupitt** [comment]
Actually, there's a test already, now I look. It should be fine now.

**Comment by augustocdias** [comment]
I've updated to the latest version and the problem is still happening

**Comment by jcupitt** [comment]
It's working for me. Perhaps your libwebp is missing metadata support? It's in a separate library.

**Comment by jcupitt** [comment]
Ooop, sorry, this is a CMYK jpeg with no ICC profile, so libvips is unable to convert it to RGB for save as webp.

It works if you give a profile, eg.:

```
vips icc_import file.jpeg x.webp --input-profile=cmyk
```

But you're right, it should use a fallback profile in this case. I'll have a look.

**Comment by jcupitt** [comment]
OK, fixed in the master and 8.10 branches, this should be in 8.10.1.

Thanks for the report!
